name: deploy-lambda-action
description: Deploy a Lambda function with container image

inputs:
  function-name:
    description: Name of Lambda function
    required: true
  image-uri:
    description: URI of Docker image
    required: false
  zip-path:
    description: Path to an archive
    required: false
  alias-name:
    description: Name of function alias (optional)
    required: false
  alias-description:
    description: Description of function alias (optional)
    required: false
    default: ref=${{ github.ref }},sha=${{ github.sha }}
  time-out:
    description: Function timeout in seconds (optional)
    required: false
  memory-size:
    description: Function memory size (optional)
    required: false
  role:
    description: Execution role for the function (optional)
    required: false

outputs:
  function-version:
    description: Published version
  function-version-arn:
    description: ARN of published version  

runs:
  using: 'node16'
  main: 'dist/index.js'
